version: '3.8'

services:
  haproxy:
    image: haproxy:lts-bookworm
    container_name: haproxy
    ports:
      - "8404:8404"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/etc/haproxy/certs
      - ./run:/var/run
    restart: always

  redis:
    image: redis:latest
    restart: always
    network_mode: host
    env_file:
      - ./.env
    entrypoint: [ "bash", "/usr/local/bin/redis.sh" ]
    volumes:
      - ./redis:/data
      - ./redis.sh:/usr/local/bin/redis.sh
